vim '+source script2.vim' releases_partition_aa
vim '+source script2.vim' releases_partition_ab
vim '+source script2.vim' releases_partition_ac
vim '+source script2.vim' releases_partition_ad
vim '+source script2.vim' releases_partition_ae
vim '+source script2.vim' releases_partition_af
vim '+source script2.vim' releases_partition_ag
vim '+source script2.vim' releases_partition_ah
vim '+source script2.vim' releases_partition_ai
vim '+source script2.vim' releases_partition_aj
vim '+source script2.vim' releases_partition_ak
vim '+source script2.vim' releases_partition_al
vim '+source script2.vim' releases_partition_am
vim '+source script2.vim' releases_partition_an
vim '+source script2.vim' releases_partition_ao
vim '+source script2.vim' releases_partition_ap
vim '+source script2.vim' releases_partition_aq
vim '+source script2.vim' releases_partition_ar
vim '+source script2.vim' releases_partition_as
vim '+source script2.vim' releases_partition_at
vim '+source script2.vim' releases_partition_au
vim '+source script2.vim' releases_partition_av
vim '+source script2.vim' releases_partition_aw
vim '+source script2.vim' releases_partition_ax
vim '+source script2.vim' releases_partition_ay
vim '+source script2.vim' releases_partition_az
