execute 'set hlsearch'
execute 'g/<genre>Jazz.*main_release="true"/y L'
execute '%d'
execute 'normal! y_"Lp'
execute 'normal! gg'
execute 'put! '
execute 'normal! I<releases>'
execute 'normal! G'
execute 'put '
execute 'normal! I</releases>'
execute 'wq'
